/* jshint globalstrict: true */
'use strict';

module.exports = {
    CLEAR_GISTS             : 'CLEAR_GISTS',
    GET_USERS_GISTS         : 'GET_USERS_GISTS',
    GET_USERS_GISTS_SUCCESS : 'GET_USERS_GISTS_SUCCESS',
    GET_USERS_GISTS_FAILURE : 'GET_USERS_GISTS_FAILURE',
    INSTANCE_CREATE         : 'INSTANCE_CREATE',
    INSTANCE_FETCH_ALL      : 'INSTANCE_FETCH_ALL',
    INSTANCE_REMOVE         : 'INSTANCE_REMOVE',
    INSTANCE_REPROVISION    : 'INSTANCE_REPROVISION',
    LOGIN                   : 'LOGIN',
    LOGIN_SUCCESSFUL        : 'LOGIN_SUCCESSFUL',
    LOGIN_FAILED            : 'LOGIN_FAILED',
    LOGOUT                  : 'LOGOUT',
    PROJECT_CREATE          : 'PROJECT_CREATE',
    PROJECT_DESTROY         : 'PROJECT_DESTROY',
    PROJECT_FETCH_ALL       : 'PROJECT_FETCH_ALL'
};
