'use strict';

module.exports = {
    ACTIVATE_BUILD              : 'ACTIVATE_BUILD',
    ACTIVATE_BUILD_SUCCESS      : 'ACTIVATE_BUILD_SUCCESS',
    BUILD_CREATE                : 'BUILD_CREATE',
    BUILD_CREATE_SUCCESS        : 'BUILD_CREATE_SUCCESS',
    CLEAR_GISTS                 : 'CLEAR_GISTS',
    CONTAINER_CREATE            : 'CONTAINER_CREATE',
    CONTAINER_CREATE_SUCCESS    : 'CONTAINER_CREATE_SUCCESS',
    CONTAINER_FETCH             : 'CONTAINER_FETCH',
    CONTAINER_FETCH_SUCCESS     : 'CONTAINER_FETCH_SUCCESS',
    CONTAINER_FETCH_ALL         : 'CONTAINER_FETCH_ALL',
    CONTAINER_FETCH_ALL_SUCCESS : 'CONTAINER_FETCH_ALL_SUCCESS',
    CONTAINER_KILL              : 'CONTAINER_KILL',
    CONTAINER_KILL_SUCCESS      : 'CONTAINER_KILL_SUCCESS',
    CONTAINER_RECREATE          : 'CONTAINER_RECREATE',
    CONTAINER_RECREATE_SUCCESS  : 'CONTAINER_RECREATE_SUCCESS',
    GET_USERS_GISTS             : 'GET_USERS_GISTS',
    GET_USERS_GISTS_SUCCESS     : 'GET_USERS_GISTS_SUCCESS',
    GET_USERS_GISTS_FAILURE     : 'GET_USERS_GISTS_FAILURE',
    LOGIN                       : 'LOGIN',
    LOGIN_SUCCESSFUL            : 'LOGIN_SUCCESSFUL',
    LOGIN_FAILED                : 'LOGIN_FAILED',
    LOGOUT                      : 'LOGOUT'
};
