'use strict';

export default {
    ACTIVATE_BUILD              : 'ACTIVATE_BUILD',
    ACTIVATE_BUILD_SUCCESS      : 'ACTIVATE_BUILD_SUCCESS',
    CLEAR_GISTS                 : 'CLEAR_GISTS',
    CREATE_BUILD                : 'CREATE_BUILD',
    CREATE_BUILD_SUCCESS        : 'CREATE_BUILD_SUCCESS',
    CONTAINER_CREATE            : 'CONTAINER_CREATE',
    CONTAINER_CREATE_SUCCESS    : 'CONTAINER_CREATE_SUCCESS',
    CONTAINER_FETCH             : 'CONTAINER_FETCH',
    CONTAINER_FETCH_SUCCESS     : 'CONTAINER_FETCH_SUCCESS',
    CONTAINER_FETCH_ALL         : 'CONTAINER_FETCH_ALL',
    CONTAINER_FETCH_ALL_SUCCESS : 'CONTAINER_FETCH_ALL_SUCCESS',
    CONTAINER_KILL              : 'CONTAINER_KILL',
    CONTAINER_KILL_SUCCESS      : 'CONTAINER_KILL_SUCCESS',
    DELETE_BUILD                : 'DELETE_BUILD',
    DELETE_BUILD_SUCCESS        : 'DELETE_BUILD_SUCCESS',
    LOGIN                       : 'LOGIN',
    LOGIN_SUCCESSFUL            : 'LOGIN_SUCCESSFUL',
    LOGIN_FAILED                : 'LOGIN_FAILED',
    LOGOUT                      : 'LOGOUT'
};
