include_recipe 'spacesynter::apt-get-update'
include_recipe 'spacesynter::nginx'
include_recipe 'spacesynter::environment'
include_recipe 'spacesynter::packages'
include_recipe 'spacesynter::servers'
